var data = {
  projects: [
    {
      Projekt: "Cloud.",
      year: "2021",
      Collobration: "Audrey Meret Lohmann, Luis Praxmarer, Lars Ziegler",
      "Mentored by": "Rasa Weber, Verena Ziegler",
      "Description ":
        "Extreme Weather conditions are increasing and climate change is a crisis. CLOUD. reflects our influence on the climate. By touching the clouds you feel the consequences. Humans have a devastating impact on the climate We should take responsibility for it. ",
      "": "",
    },
    {
      Projekt: "Interactive Visualisations",
      Year: "2021",
      Collobration: "–",
      "Mentored by": "Rebecca Morganti-Pfaffhauser",
      "Description ": "xxx ",
      "": "",
    },
    {
      Projekt: "Computer of the Mouth",
      Year: "2023",
      Collobration: "Jan Philipp Künne, Alexander Mazzone",
      "Mentored by": "Luke Franzke",
      "Description ": "xxx ",
      "": "",
    },
    {
      Projekt: "tan&tum",
      Year: "2020",
      Collobration: "Célina Streun, Jana Buchmann",
      "Mentored by": "Lucas Äschlimann, Ralph Harb",
      "Description ":
        'The experimental, minimalist, and paradoxical magazine "tan&tum" was developed as an interdisciplinary design project for the vocational baccalaureate. It was a collaborative effort involving three colleagues, with each member contributing their expertise to various aspects of the project. The magazine comprised 88 pages, meticulously crafted to reflect our deep exploration of minimalism. Central to our project was an investigation into consumer behavior and its implications. We delved into questions such as "What defines minimalism?" and "Is our current level of consumerism sustainable or even desirable?" Through thoughtful exploration, we challenged assumptions about the relationship between possessions and happiness. This critical examination of minimalism and consumerism was not only reflected in the content but also intricately woven into the design of the magazine itself. The layout, typography, and overall aesthetic were all carefully considered to convey our thematic message. ',
      "": "",
    },
    {
      Projekt: "Around the Sun",
      Year: "2022",
      Collobration: "Joël Borter, Gabriel Schaller",
      "Mentored by": "Michael Stünzi, Daniel Röttele",
      "Description ": "xxx",
      "": "",
    },
    {
      Projekt: "",
      Year: "",
      Collobration: "",
      "Mentored by": "",
      "Description ": "",
      "": "",
    },
    {
      Projekt: "",
      Year: "",
      Collobration: "",
      "Mentored by": "",
      "Description ": "",
      "": "",
    },
    {
      Projekt: "",
      Year: "",
      Collobration: "",
      "Mentored by": "",
      "Description ": "",
      "": "",
    },
    {
      Projekt: "",
      Year: "",
      Collobration: "",
      "Mentored by": "",
      "Description ": "",
      "": "",
    },
  ],
};
